seed: 42
n_classes: 7

cv:
  batch_size: 32
  model_name: "efficientnet-b4"
  evaluate:
    model_path: "epoch-39-efficientnet-b4-checkpoint.pt
"
    coef: 0.39330984840728656

nlp:
  batch_size: 8
  model_name: 'youscan/ukr-roberta-base'
  max_seq_len: 512
  evaluate:
    model_path: "epoch-11-youscan-ukr-roberta-base-checkpoint.pt"
    coef: 0.6066901515927133
