seed: 42
n_classes: 7

cv:
  batch_size: 32
  model_name: "efficientnet-b4"
  evaluate:
    model_path: "epoch-39-efficientnet-b4-checkpoint.pt"
    coef: 0.5

nlp:
  batch_size: 6
  model_name: 'xlm-roberta-base'
  max_seq_len: 512
  evaluate:
    model_path: "epoch-9-xlm-roberta-base-checkpoint.pt"
    coef: 0.89
