seed: 2021
batch_size: 6
# model_name: 'youscan/ukr-roberta-base'
# model_name: 'roberta-large-mnli'
# model_name: 'deepset/roberta-base-squad2'
model_name: 'xlm-roberta-base'
# model_name: 'albert-xxlarge-v2'
max_seq_len: 512
n_classes: 7
train:
  train_folds:
    - 0
    - 1
    - 3
    - 4
  val_folds:
    - 2
  epochs: 10
evaluate:
  model_path: "epoch-9-xlm-roberta-base-checkpoint.pt"
