seed: 42
batch_size: 8
model_name: 'youscan/ukr-roberta-base'
max_seq_len: 512
n_classes: 7
train:
  train_folds:
    - 0
    - 1
    - 3
    - 4
  val_folds:
    - 2
#  learning_rate: 0.005
  epochs: 30
evaluate:
  model_path: "epoch-11-youscan-ukr-roberta-base-checkpoint.pt"
